// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: buyer.proto

package buyer

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "wildberries/pkg/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Buyer: текущая акция ---
// GET /promotions/current
type GetCurrentPromotionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPromotionRequest) Reset() {
	*x = GetCurrentPromotionRequest{}
	mi := &file_buyer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPromotionRequest) ProtoMessage() {}

func (x *GetCurrentPromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPromotionRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPromotionRequest) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{0}
}

type GetCurrentPromotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Theme         string                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                     // RUNNING
	DateFrom      string                 `protobuf:"bytes,6,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"` // RFC3339
	DateTo        string                 `protobuf:"bytes,7,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Segments      []*common.Segment      `protobuf:"bytes,8,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPromotionResponse) Reset() {
	*x = GetCurrentPromotionResponse{}
	mi := &file_buyer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPromotionResponse) ProtoMessage() {}

func (x *GetCurrentPromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPromotionResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentPromotionResponse) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentPromotionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCurrentPromotionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCurrentPromotionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetCurrentPromotionResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *GetCurrentPromotionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCurrentPromotionResponse) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetCurrentPromotionResponse) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetCurrentPromotionResponse) GetSegments() []*common.Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

// --- Buyer: продукты сегмента ---
// GET /promotions/{promotionId}/segments/{segmentId}/products
type GetSegmentProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   int64                  `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	SegmentId     int64                  `protobuf:"varint,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                                 // filter
	OnlyDiscounts bool                   `protobuf:"varint,4,opt,name=only_discounts,json=onlyDiscounts,proto3" json:"only_discounts,omitempty"` // filter
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`                                         // e.g. price_asc, discount_desc
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,7,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentProductsRequest) Reset() {
	*x = GetSegmentProductsRequest{}
	mi := &file_buyer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentProductsRequest) ProtoMessage() {}

func (x *GetSegmentProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentProductsRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentProductsRequest) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{2}
}

func (x *GetSegmentProductsRequest) GetPromotionId() int64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *GetSegmentProductsRequest) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *GetSegmentProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetSegmentProductsRequest) GetOnlyDiscounts() bool {
	if x != nil {
		return x.OnlyDiscounts
	}
	return false
}

func (x *GetSegmentProductsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetSegmentProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSegmentProductsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetSegmentProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*common.ProductItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Completed     bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"` // акция завершена
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentProductsResponse) Reset() {
	*x = GetSegmentProductsResponse{}
	mi := &file_buyer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentProductsResponse) ProtoMessage() {}

func (x *GetSegmentProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentProductsResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentProductsResponse) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{3}
}

func (x *GetSegmentProductsResponse) GetItems() []*common.ProductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetSegmentProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSegmentProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSegmentProductsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetSegmentProductsResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

// --- Identification ---
// POST /identification/start
type StartIdentificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   int64                  `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartIdentificationRequest) Reset() {
	*x = StartIdentificationRequest{}
	mi := &file_buyer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartIdentificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIdentificationRequest) ProtoMessage() {}

func (x *StartIdentificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIdentificationRequest.ProtoReflect.Descriptor instead.
func (*StartIdentificationRequest) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{4}
}

func (x *StartIdentificationRequest) GetPromotionId() int64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

type PollQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []*PollOption          `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollQuestion) Reset() {
	*x = PollQuestion{}
	mi := &file_buyer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollQuestion) ProtoMessage() {}

func (x *PollQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollQuestion.ProtoReflect.Descriptor instead.
func (*PollQuestion) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{5}
}

func (x *PollQuestion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PollQuestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PollQuestion) GetOptions() []*PollOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type PollOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOption) Reset() {
	*x = PollOption{}
	mi := &file_buyer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOption) ProtoMessage() {}

func (x *PollOption) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOption.ProtoReflect.Descriptor instead.
func (*PollOption) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{6}
}

func (x *PollOption) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PollOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PollOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StartIdentificationResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // "questions" | "user_profile"
	// Types that are valid to be assigned to PollOrSegment:
	//
	//	*StartIdentificationResponse_Poll
	//	*StartIdentificationResponse_ResultSegmentId
	PollOrSegment isStartIdentificationResponse_PollOrSegment `protobuf_oneof:"poll_or_segment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartIdentificationResponse) Reset() {
	*x = StartIdentificationResponse{}
	mi := &file_buyer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartIdentificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIdentificationResponse) ProtoMessage() {}

func (x *StartIdentificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIdentificationResponse.ProtoReflect.Descriptor instead.
func (*StartIdentificationResponse) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{7}
}

func (x *StartIdentificationResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StartIdentificationResponse) GetPollOrSegment() isStartIdentificationResponse_PollOrSegment {
	if x != nil {
		return x.PollOrSegment
	}
	return nil
}

func (x *StartIdentificationResponse) GetPoll() *Poll {
	if x != nil {
		if x, ok := x.PollOrSegment.(*StartIdentificationResponse_Poll); ok {
			return x.Poll
		}
	}
	return nil
}

func (x *StartIdentificationResponse) GetResultSegmentId() int64 {
	if x != nil {
		if x, ok := x.PollOrSegment.(*StartIdentificationResponse_ResultSegmentId); ok {
			return x.ResultSegmentId
		}
	}
	return 0
}

type isStartIdentificationResponse_PollOrSegment interface {
	isStartIdentificationResponse_PollOrSegment()
}

type StartIdentificationResponse_Poll struct {
	Poll *Poll `protobuf:"bytes,2,opt,name=poll,proto3,oneof"` // для method=questions
}

type StartIdentificationResponse_ResultSegmentId struct {
	ResultSegmentId int64 `protobuf:"varint,3,opt,name=result_segment_id,json=resultSegmentId,proto3,oneof"` // для method=user_profile (заглушка — случайный)
}

func (*StartIdentificationResponse_Poll) isStartIdentificationResponse_PollOrSegment() {}

func (*StartIdentificationResponse_ResultSegmentId) isStartIdentificationResponse_PollOrSegment() {}

type Poll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*PollQuestion        `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_buyer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{8}
}

func (x *Poll) GetQuestions() []*PollQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

// POST /identification/answer
type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   int64                  `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	OptionId      int64                  `protobuf:"varint,3,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_buyer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{9}
}

func (x *AnswerRequest) GetPromotionId() int64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *AnswerRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AnswerRequest) GetOptionId() int64 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

type AnswerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NextQuestionId  int64                  `protobuf:"varint,1,opt,name=next_question_id,json=nextQuestionId,proto3" json:"next_question_id,omitempty"`    // 0 если нет следующего
	ResultSegmentId int64                  `protobuf:"varint,2,opt,name=result_segment_id,json=resultSegmentId,proto3" json:"result_segment_id,omitempty"` // 0 если ещё не финал
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_buyer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buyer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_buyer_proto_rawDescGZIP(), []int{10}
}

func (x *AnswerResponse) GetNextQuestionId() int64 {
	if x != nil {
		return x.NextQuestionId
	}
	return 0
}

func (x *AnswerResponse) GetResultSegmentId() int64 {
	if x != nil {
		return x.ResultSegmentId
	}
	return 0
}

var File_buyer_proto protoreflect.FileDescriptor

const file_buyer_proto_rawDesc = "" +
	"\n" +
	"\vbuyer.proto\x12\x11wildberries.buyer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x1c\n" +
	"\x1aGetCurrentPromotionRequest\"\x80\x02\n" +
	"\x1bGetCurrentPromotionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05theme\x18\x04 \x01(\tR\x05theme\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tdate_from\x18\x06 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\a \x01(\tR\x06dateTo\x127\n" +
	"\bsegments\x18\b \x03(\v2\x1b.wildberries.common.SegmentR\bsegments\"\xe3\x01\n" +
	"\x19GetSegmentProductsRequest\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\x03R\vpromotionId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\x03R\tsegmentId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12%\n" +
	"\x0eonly_discounts\x18\x04 \x01(\bR\ronlyDiscounts\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\a \x01(\x05R\aperPage\"\xb6\x01\n" +
	"\x1aGetSegmentProductsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.wildberries.common.ProductItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\"?\n" +
	"\x1aStartIdentificationRequest\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\x03R\vpromotionId\"k\n" +
	"\fPollQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x127\n" +
	"\aoptions\x18\x03 \x03(\v2\x1d.wildberries.buyer.PollOptionR\aoptions\"F\n" +
	"\n" +
	"PollOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xa5\x01\n" +
	"\x1bStartIdentificationResponse\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12-\n" +
	"\x04poll\x18\x02 \x01(\v2\x17.wildberries.buyer.PollH\x00R\x04poll\x12,\n" +
	"\x11result_segment_id\x18\x03 \x01(\x03H\x00R\x0fresultSegmentIdB\x11\n" +
	"\x0fpoll_or_segment\"E\n" +
	"\x04Poll\x12=\n" +
	"\tquestions\x18\x01 \x03(\v2\x1f.wildberries.buyer.PollQuestionR\tquestions\"p\n" +
	"\rAnswerRequest\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\x03R\vpromotionId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12\x1b\n" +
	"\toption_id\x18\x03 \x01(\x03R\boptionId\"f\n" +
	"\x0eAnswerResponse\x12(\n" +
	"\x10next_question_id\x18\x01 \x01(\x03R\x0enextQuestionId\x12*\n" +
	"\x11result_segment_id\x18\x02 \x01(\x03R\x0fresultSegmentId2\xac\x05\n" +
	"\x15BuyerPromotionService\x12\xa7\x02\n" +
	"\x13GetCurrentPromotion\x12-.wildberries.buyer.GetCurrentPromotionRequest\x1a..wildberries.buyer.GetCurrentPromotionResponse\"\xb0\x01\x92A\x91\x01\n" +
	"\n" +
	"Promotions\x12*Получить текущую акцию\x1aBПолучает информацию о текущей акции*\x13GetCurrentPromotion\x82\xd3\xe4\x93\x02\x15\x12\x13/promotions/current\x12\xe8\x02\n" +
	"\x12GetSegmentProducts\x12,.wildberries.buyer.GetSegmentProductsRequest\x1a-.wildberries.buyer.GetSegmentProductsResponse\"\xf4\x01\x92A\xaf\x01\n" +
	"\bProducts\x122Получить продукты сегмента\x1a[Получает список продуктов для заданного сегмента*\x12GetSegmentProducts\x82\xd3\xe4\x93\x02;\x129/promotions/{promotion_id}/segments/{segment_id}/products2\xb8\x04\n" +
	"\x15IdentificationService\x12\xba\x02\n" +
	"\x13StartIdentification\x12-.wildberries.buyer.StartIdentificationRequest\x1a..wildberries.buyer.StartIdentificationResponse\"\xc3\x01\x92A\x9f\x01\n" +
	"\x0eIdentification\x12'Начать идентификацию\x1aOНачинает процесс идентификации покупателя*\x13StartIdentification\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/identification/start\x12\xe1\x01\n" +
	"\x06Answer\x12 .wildberries.buyer.AnswerRequest\x1a!.wildberries.buyer.AnswerResponse\"\x91\x01\x92Am\n" +
	"\x0eIdentification\x12\"Ответить на вопрос\x1a/Отвечает на вопрос опроса*\x06Answer\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/identification/answerB\xbe\x01\x92A\x9d\x01\x12d\n" +
	"\x12Buyer сервис\x12GСервис покупателя для работы с акциями2\x051.0.0\x1a\x0elocalhost:7001*\x01\x012\x10application/json:\x10application/jsonZ\x1bwildberries/pkg/buyer;buyerb\x06proto3"

var (
	file_buyer_proto_rawDescOnce sync.Once
	file_buyer_proto_rawDescData []byte
)

func file_buyer_proto_rawDescGZIP() []byte {
	file_buyer_proto_rawDescOnce.Do(func() {
		file_buyer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_buyer_proto_rawDesc), len(file_buyer_proto_rawDesc)))
	})
	return file_buyer_proto_rawDescData
}

var file_buyer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_buyer_proto_goTypes = []any{
	(*GetCurrentPromotionRequest)(nil),  // 0: wildberries.buyer.GetCurrentPromotionRequest
	(*GetCurrentPromotionResponse)(nil), // 1: wildberries.buyer.GetCurrentPromotionResponse
	(*GetSegmentProductsRequest)(nil),   // 2: wildberries.buyer.GetSegmentProductsRequest
	(*GetSegmentProductsResponse)(nil),  // 3: wildberries.buyer.GetSegmentProductsResponse
	(*StartIdentificationRequest)(nil),  // 4: wildberries.buyer.StartIdentificationRequest
	(*PollQuestion)(nil),                // 5: wildberries.buyer.PollQuestion
	(*PollOption)(nil),                  // 6: wildberries.buyer.PollOption
	(*StartIdentificationResponse)(nil), // 7: wildberries.buyer.StartIdentificationResponse
	(*Poll)(nil),                        // 8: wildberries.buyer.Poll
	(*AnswerRequest)(nil),               // 9: wildberries.buyer.AnswerRequest
	(*AnswerResponse)(nil),              // 10: wildberries.buyer.AnswerResponse
	(*common.Segment)(nil),              // 11: wildberries.common.Segment
	(*common.ProductItem)(nil),          // 12: wildberries.common.ProductItem
}
var file_buyer_proto_depIdxs = []int32{
	11, // 0: wildberries.buyer.GetCurrentPromotionResponse.segments:type_name -> wildberries.common.Segment
	12, // 1: wildberries.buyer.GetSegmentProductsResponse.items:type_name -> wildberries.common.ProductItem
	6,  // 2: wildberries.buyer.PollQuestion.options:type_name -> wildberries.buyer.PollOption
	8,  // 3: wildberries.buyer.StartIdentificationResponse.poll:type_name -> wildberries.buyer.Poll
	5,  // 4: wildberries.buyer.Poll.questions:type_name -> wildberries.buyer.PollQuestion
	0,  // 5: wildberries.buyer.BuyerPromotionService.GetCurrentPromotion:input_type -> wildberries.buyer.GetCurrentPromotionRequest
	2,  // 6: wildberries.buyer.BuyerPromotionService.GetSegmentProducts:input_type -> wildberries.buyer.GetSegmentProductsRequest
	4,  // 7: wildberries.buyer.IdentificationService.StartIdentification:input_type -> wildberries.buyer.StartIdentificationRequest
	9,  // 8: wildberries.buyer.IdentificationService.Answer:input_type -> wildberries.buyer.AnswerRequest
	1,  // 9: wildberries.buyer.BuyerPromotionService.GetCurrentPromotion:output_type -> wildberries.buyer.GetCurrentPromotionResponse
	3,  // 10: wildberries.buyer.BuyerPromotionService.GetSegmentProducts:output_type -> wildberries.buyer.GetSegmentProductsResponse
	7,  // 11: wildberries.buyer.IdentificationService.StartIdentification:output_type -> wildberries.buyer.StartIdentificationResponse
	10, // 12: wildberries.buyer.IdentificationService.Answer:output_type -> wildberries.buyer.AnswerResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_buyer_proto_init() }
func file_buyer_proto_init() {
	if File_buyer_proto != nil {
		return
	}
	file_buyer_proto_msgTypes[7].OneofWrappers = []any{
		(*StartIdentificationResponse_Poll)(nil),
		(*StartIdentificationResponse_ResultSegmentId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_buyer_proto_rawDesc), len(file_buyer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_buyer_proto_goTypes,
		DependencyIndexes: file_buyer_proto_depIdxs,
		MessageInfos:      file_buyer_proto_msgTypes,
	}.Build()
	File_buyer_proto = out.File
	file_buyer_proto_goTypes = nil
	file_buyer_proto_depIdxs = nil
}
