// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: buyer.proto

package buyer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BuyerPromotionService_GetCurrentPromotion_FullMethodName = "/wildberries.buyer.BuyerPromotionService/GetCurrentPromotion"
	BuyerPromotionService_GetSegmentProducts_FullMethodName  = "/wildberries.buyer.BuyerPromotionService/GetSegmentProducts"
)

// BuyerPromotionServiceClient is the client API for BuyerPromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuyerPromotionServiceClient interface {
	GetCurrentPromotion(ctx context.Context, in *GetCurrentPromotionRequest, opts ...grpc.CallOption) (*GetCurrentPromotionResponse, error)
	GetSegmentProducts(ctx context.Context, in *GetSegmentProductsRequest, opts ...grpc.CallOption) (*GetSegmentProductsResponse, error)
}

type buyerPromotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuyerPromotionServiceClient(cc grpc.ClientConnInterface) BuyerPromotionServiceClient {
	return &buyerPromotionServiceClient{cc}
}

func (c *buyerPromotionServiceClient) GetCurrentPromotion(ctx context.Context, in *GetCurrentPromotionRequest, opts ...grpc.CallOption) (*GetCurrentPromotionResponse, error) {
	out := new(GetCurrentPromotionResponse)
	err := c.cc.Invoke(ctx, BuyerPromotionService_GetCurrentPromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buyerPromotionServiceClient) GetSegmentProducts(ctx context.Context, in *GetSegmentProductsRequest, opts ...grpc.CallOption) (*GetSegmentProductsResponse, error) {
	out := new(GetSegmentProductsResponse)
	err := c.cc.Invoke(ctx, BuyerPromotionService_GetSegmentProducts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuyerPromotionServiceServer is the server API for BuyerPromotionService service.
// All implementations must embed UnimplementedBuyerPromotionServiceServer
// for forward compatibility
type BuyerPromotionServiceServer interface {
	GetCurrentPromotion(context.Context, *GetCurrentPromotionRequest) (*GetCurrentPromotionResponse, error)
	GetSegmentProducts(context.Context, *GetSegmentProductsRequest) (*GetSegmentProductsResponse, error)
	mustEmbedUnimplementedBuyerPromotionServiceServer()
}

// UnimplementedBuyerPromotionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBuyerPromotionServiceServer struct {
}

func (UnimplementedBuyerPromotionServiceServer) GetCurrentPromotion(context.Context, *GetCurrentPromotionRequest) (*GetCurrentPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPromotion not implemented")
}
func (UnimplementedBuyerPromotionServiceServer) GetSegmentProducts(context.Context, *GetSegmentProductsRequest) (*GetSegmentProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSegmentProducts not implemented")
}
func (UnimplementedBuyerPromotionServiceServer) mustEmbedUnimplementedBuyerPromotionServiceServer() {}

// UnsafeBuyerPromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuyerPromotionServiceServer will
// result in compilation errors.
type UnsafeBuyerPromotionServiceServer interface {
	mustEmbedUnimplementedBuyerPromotionServiceServer()
}

func RegisterBuyerPromotionServiceServer(s grpc.ServiceRegistrar, srv BuyerPromotionServiceServer) {
	s.RegisterService(&BuyerPromotionService_ServiceDesc, srv)
}

func _BuyerPromotionService_GetCurrentPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuyerPromotionServiceServer).GetCurrentPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuyerPromotionService_GetCurrentPromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuyerPromotionServiceServer).GetCurrentPromotion(ctx, req.(*GetCurrentPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuyerPromotionService_GetSegmentProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuyerPromotionServiceServer).GetSegmentProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuyerPromotionService_GetSegmentProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuyerPromotionServiceServer).GetSegmentProducts(ctx, req.(*GetSegmentProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuyerPromotionService_ServiceDesc is the grpc.ServiceDesc for BuyerPromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuyerPromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.buyer.BuyerPromotionService",
	HandlerType: (*BuyerPromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentPromotion",
			Handler:    _BuyerPromotionService_GetCurrentPromotion_Handler,
		},
		{
			MethodName: "GetSegmentProducts",
			Handler:    _BuyerPromotionService_GetSegmentProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buyer.proto",
}

const (
	IdentificationService_StartIdentification_FullMethodName = "/wildberries.buyer.IdentificationService/StartIdentification"
	IdentificationService_Answer_FullMethodName              = "/wildberries.buyer.IdentificationService/Answer"
)

// IdentificationServiceClient is the client API for IdentificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentificationServiceClient interface {
	StartIdentification(ctx context.Context, in *StartIdentificationRequest, opts ...grpc.CallOption) (*StartIdentificationResponse, error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error)
}

type identificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentificationServiceClient(cc grpc.ClientConnInterface) IdentificationServiceClient {
	return &identificationServiceClient{cc}
}

func (c *identificationServiceClient) StartIdentification(ctx context.Context, in *StartIdentificationRequest, opts ...grpc.CallOption) (*StartIdentificationResponse, error) {
	out := new(StartIdentificationResponse)
	err := c.cc.Invoke(ctx, IdentificationService_StartIdentification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identificationServiceClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*AnswerResponse, error) {
	out := new(AnswerResponse)
	err := c.cc.Invoke(ctx, IdentificationService_Answer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentificationServiceServer is the server API for IdentificationService service.
// All implementations must embed UnimplementedIdentificationServiceServer
// for forward compatibility
type IdentificationServiceServer interface {
	StartIdentification(context.Context, *StartIdentificationRequest) (*StartIdentificationResponse, error)
	Answer(context.Context, *AnswerRequest) (*AnswerResponse, error)
	mustEmbedUnimplementedIdentificationServiceServer()
}

// UnimplementedIdentificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdentificationServiceServer struct {
}

func (UnimplementedIdentificationServiceServer) StartIdentification(context.Context, *StartIdentificationRequest) (*StartIdentificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartIdentification not implemented")
}
func (UnimplementedIdentificationServiceServer) Answer(context.Context, *AnswerRequest) (*AnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedIdentificationServiceServer) mustEmbedUnimplementedIdentificationServiceServer() {}

// UnsafeIdentificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentificationServiceServer will
// result in compilation errors.
type UnsafeIdentificationServiceServer interface {
	mustEmbedUnimplementedIdentificationServiceServer()
}

func RegisterIdentificationServiceServer(s grpc.ServiceRegistrar, srv IdentificationServiceServer) {
	s.RegisterService(&IdentificationService_ServiceDesc, srv)
}

func _IdentificationService_StartIdentification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartIdentificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentificationServiceServer).StartIdentification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentificationService_StartIdentification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentificationServiceServer).StartIdentification(ctx, req.(*StartIdentificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentificationService_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentificationServiceServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentificationService_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentificationServiceServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentificationService_ServiceDesc is the grpc.ServiceDesc for IdentificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.buyer.IdentificationService",
	HandlerType: (*IdentificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartIdentification",
			Handler:    _IdentificationService_StartIdentification_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _IdentificationService_Answer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buyer.proto",
}
