// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: common.proto

package common

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromotionStatus
type PromotionStatus int32

const (
	PromotionStatus_PROMOTION_STATUS_UNSPECIFIED PromotionStatus = 0
	PromotionStatus_NOT_READY                    PromotionStatus = 1
	PromotionStatus_READY_TO_START               PromotionStatus = 2
	PromotionStatus_RUNNING                      PromotionStatus = 3
	PromotionStatus_PAUSED                       PromotionStatus = 4
	PromotionStatus_COMPLETED                    PromotionStatus = 5
)

// Enum value maps for PromotionStatus.
var (
	PromotionStatus_name = map[int32]string{
		0: "PROMOTION_STATUS_UNSPECIFIED",
		1: "NOT_READY",
		2: "READY_TO_START",
		3: "RUNNING",
		4: "PAUSED",
		5: "COMPLETED",
	}
	PromotionStatus_value = map[string]int32{
		"PROMOTION_STATUS_UNSPECIFIED": 0,
		"NOT_READY":                    1,
		"READY_TO_START":               2,
		"RUNNING":                      3,
		"PAUSED":                       4,
		"COMPLETED":                    5,
	}
)

func (x PromotionStatus) Enum() *PromotionStatus {
	p := new(PromotionStatus)
	*p = x
	return p
}

func (x PromotionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PromotionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (PromotionStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x PromotionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PromotionStatus.Descriptor instead.
func (PromotionStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// IdentificationMode
type IdentificationMode int32

const (
	IdentificationMode_IDENTIFICATION_MODE_UNSPECIFIED IdentificationMode = 0
	IdentificationMode_QUESTIONS                       IdentificationMode = 1
	IdentificationMode_USER_PROFILE                    IdentificationMode = 2
)

// Enum value maps for IdentificationMode.
var (
	IdentificationMode_name = map[int32]string{
		0: "IDENTIFICATION_MODE_UNSPECIFIED",
		1: "QUESTIONS",
		2: "USER_PROFILE",
	}
	IdentificationMode_value = map[string]int32{
		"IDENTIFICATION_MODE_UNSPECIFIED": 0,
		"QUESTIONS":                       1,
		"USER_PROFILE":                    2,
	}
)

func (x IdentificationMode) Enum() *IdentificationMode {
	p := new(IdentificationMode)
	*p = x
	return p
}

func (x IdentificationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentificationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (IdentificationMode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x IdentificationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentificationMode.Descriptor instead.
func (IdentificationMode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// PricingModel
type PricingModel int32

const (
	PricingModel_PRICING_MODEL_UNSPECIFIED PricingModel = 0
	PricingModel_AUCTION                   PricingModel = 1
	PricingModel_FIXED                     PricingModel = 2
)

// Enum value maps for PricingModel.
var (
	PricingModel_name = map[int32]string{
		0: "PRICING_MODEL_UNSPECIFIED",
		1: "AUCTION",
		2: "FIXED",
	}
	PricingModel_value = map[string]int32{
		"PRICING_MODEL_UNSPECIFIED": 0,
		"AUCTION":                   1,
		"FIXED":                     2,
	}
)

func (x PricingModel) Enum() *PricingModel {
	p := new(PricingModel)
	*p = x
	return p
}

func (x PricingModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PricingModel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (PricingModel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x PricingModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PricingModel.Descriptor instead.
func (PricingModel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// Segment — сегмент акции (знак зодиака, факультет и т.д.)
type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryName  string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,4,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"` // опционально, для AI-текста
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Segment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segment) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Segment) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Segment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ProductItem — товар в ответах (витрина, модерация)
type ProductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice      int64                  `protobuf:"varint,5,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	Discount      int32                  `protobuf:"varint,6,opt,name=discount,proto3" json:"discount,omitempty"`
	Badge         string                 `protobuf:"bytes,7,opt,name=badge,proto3" json:"badge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItem) Reset() {
	*x = ProductItem{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItem) ProtoMessage() {}

func (x *ProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItem.ProtoReflect.Descriptor instead.
func (*ProductItem) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProductItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductItem) GetOldPrice() int64 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

func (x *ProductItem) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *ProductItem) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

// StopFactors — список стоп-факторов (JSON array of strings в БД)
type StopFactors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factors       []string               `protobuf:"bytes,1,rep,name=factors,proto3" json:"factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopFactors) Reset() {
	*x = StopFactors{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopFactors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFactors) ProtoMessage() {}

func (x *StopFactors) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFactors.ProtoReflect.Descriptor instead.
func (*StopFactors) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *StopFactors) GetFactors() []string {
	if x != nil {
		return x.Factors
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x12wildberries.common\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x87\x01\n" +
	"\aSegment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12\x1f\n" +
	"\vorder_index\x18\x04 \x01(\x05R\n" +
	"orderIndex\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"\xac\x01\n" +
	"\vProductItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1b\n" +
	"\told_price\x18\x05 \x01(\x03R\boldPrice\x12\x1a\n" +
	"\bdiscount\x18\x06 \x01(\x05R\bdiscount\x12\x14\n" +
	"\x05badge\x18\a \x01(\tR\x05badge\"'\n" +
	"\vStopFactors\x12\x18\n" +
	"\afactors\x18\x01 \x03(\tR\afactors*~\n" +
	"\x0fPromotionStatus\x12 \n" +
	"\x1cPROMOTION_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tNOT_READY\x10\x01\x12\x12\n" +
	"\x0eREADY_TO_START\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05*Z\n" +
	"\x12IdentificationMode\x12#\n" +
	"\x1fIDENTIFICATION_MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tQUESTIONS\x10\x01\x12\x10\n" +
	"\fUSER_PROFILE\x10\x02*E\n" +
	"\fPricingModel\x12\x1d\n" +
	"\x19PRICING_MODEL_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAUCTION\x10\x01\x12\t\n" +
	"\x05FIXED\x10\x02B\xbf\x01\x92A\x9c\x01\x12c\n" +
	"\x13Common модели\x12EОбщие модели данных для всех сервисов2\x051.0.0\x1a\x0elocalhost:7000*\x01\x012\x10application/json:\x10application/jsonZ\x1dwildberries/pkg/common;commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(PromotionStatus)(0),    // 0: wildberries.common.PromotionStatus
	(IdentificationMode)(0), // 1: wildberries.common.IdentificationMode
	(PricingModel)(0),       // 2: wildberries.common.PricingModel
	(*Segment)(nil),         // 3: wildberries.common.Segment
	(*ProductItem)(nil),     // 4: wildberries.common.ProductItem
	(*StopFactors)(nil),     // 5: wildberries.common.StopFactors
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
