// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: ai.proto

package ai

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- POST /ai/themes ---
type GenerateThemesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateThemesRequest) Reset() {
	*x = GenerateThemesRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateThemesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateThemesRequest) ProtoMessage() {}

func (x *GenerateThemesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateThemesRequest.ProtoReflect.Descriptor instead.
func (*GenerateThemesRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

type ThemeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // machine name, e.g. zodiac, harry-potter
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeItem) Reset() {
	*x = ThemeItem{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeItem) ProtoMessage() {}

func (x *ThemeItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeItem.ProtoReflect.Descriptor instead.
func (*ThemeItem) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ThemeItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ThemeItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GenerateThemesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Themes        []*ThemeItem           `protobuf:"bytes,1,rep,name=themes,proto3" json:"themes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateThemesResponse) Reset() {
	*x = GenerateThemesResponse{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateThemesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateThemesResponse) ProtoMessage() {}

func (x *GenerateThemesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateThemesResponse.ProtoReflect.Descriptor instead.
func (*GenerateThemesResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateThemesResponse) GetThemes() []*ThemeItem {
	if x != nil {
		return x.Themes
	}
	return nil
}

// --- POST /ai/segments ---
type GenerateSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSegmentsRequest) Reset() {
	*x = GenerateSegmentsRequest{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSegmentsRequest) ProtoMessage() {}

func (x *GenerateSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSegmentsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateSegmentsRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *GenerateSegmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SegmentSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentSuggestion) Reset() {
	*x = SegmentSuggestion{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentSuggestion) ProtoMessage() {}

func (x *SegmentSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentSuggestion.ProtoReflect.Descriptor instead.
func (*SegmentSuggestion) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentSuggestion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SegmentSuggestion) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type GenerateSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentSuggestion   `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSegmentsResponse) Reset() {
	*x = GenerateSegmentsResponse{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSegmentsResponse) ProtoMessage() {}

func (x *GenerateSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSegmentsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateSegmentsResponse) GetSegments() []*SegmentSuggestion {
	if x != nil {
		return x.Segments
	}
	return nil
}

// --- POST /ai/questions ---
type GenerateQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsRequest) Reset() {
	*x = GenerateQuestionsRequest{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsRequest) ProtoMessage() {}

func (x *GenerateQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateQuestionsRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type QuestionSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Options       []*OptionSuggestion    `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionSuggestion) Reset() {
	*x = QuestionSuggestion{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionSuggestion) ProtoMessage() {}

func (x *QuestionSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionSuggestion.ProtoReflect.Descriptor instead.
func (*QuestionSuggestion) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionSuggestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionSuggestion) GetOptions() []*OptionSuggestion {
	if x != nil {
		return x.Options
	}
	return nil
}

type OptionSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionSuggestion) Reset() {
	*x = OptionSuggestion{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionSuggestion) ProtoMessage() {}

func (x *OptionSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionSuggestion.ProtoReflect.Descriptor instead.
func (*OptionSuggestion) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *OptionSuggestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OptionSuggestion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GenerateQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionSuggestion  `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsResponse) Reset() {
	*x = GenerateQuestionsResponse{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsResponse) ProtoMessage() {}

func (x *GenerateQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateQuestionsResponse) GetQuestions() []*QuestionSuggestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

// --- POST /ai/answer-tree ---
type GenerateAnswerTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAnswerTreeRequest) Reset() {
	*x = GenerateAnswerTreeRequest{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAnswerTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAnswerTreeRequest) ProtoMessage() {}

func (x *GenerateAnswerTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAnswerTreeRequest.ProtoReflect.Descriptor instead.
func (*GenerateAnswerTreeRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateAnswerTreeRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type AnswerTreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ParentNodeId  string                 `protobuf:"bytes,2,opt,name=parent_node_id,json=parentNodeId,proto3" json:"parent_node_id,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerTreeNode) Reset() {
	*x = AnswerTreeNode{}
	mi := &file_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerTreeNode) ProtoMessage() {}

func (x *AnswerTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerTreeNode.ProtoReflect.Descriptor instead.
func (*AnswerTreeNode) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{11}
}

func (x *AnswerTreeNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AnswerTreeNode) GetParentNodeId() string {
	if x != nil {
		return x.ParentNodeId
	}
	return ""
}

func (x *AnswerTreeNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AnswerTreeNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GenerateAnswerTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*AnswerTreeNode      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAnswerTreeResponse) Reset() {
	*x = GenerateAnswerTreeResponse{}
	mi := &file_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAnswerTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAnswerTreeResponse) ProtoMessage() {}

func (x *GenerateAnswerTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAnswerTreeResponse.ProtoReflect.Descriptor instead.
func (*GenerateAnswerTreeResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateAnswerTreeResponse) GetNodes() []*AnswerTreeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// --- POST /ai/get-text ---
type GetTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. theme, segment_name
	SegmentId     int64                  `protobuf:"varint,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`                                                   // optional, для обновления текста сегмента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextRequest) Reset() {
	*x = GetTextRequest{}
	mi := &file_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextRequest) ProtoMessage() {}

func (x *GetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextRequest.ProtoReflect.Descriptor instead.
func (*GetTextRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{13}
}

func (x *GetTextRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GetTextRequest) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

type GetTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	mi := &file_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResponse.ProtoReflect.Descriptor instead.
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{14}
}

func (x *GetTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x0ewildberries.ai\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x17\n" +
	"\x15GenerateThemesRequest\"7\n" +
	"\tThemeItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"K\n" +
	"\x16GenerateThemesResponse\x121\n" +
	"\x06themes\x18\x01 \x03(\v2\x19.wildberries.ai.ThemeItemR\x06themes\"E\n" +
	"\x17GenerateSegmentsRequest\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x11SegmentSuggestion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"Y\n" +
	"\x18GenerateSegmentsResponse\x12=\n" +
	"\bsegments\x18\x01 \x03(\v2!.wildberries.ai.SegmentSuggestionR\bsegments\"0\n" +
	"\x18GenerateQuestionsRequest\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\"d\n" +
	"\x12QuestionSuggestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12:\n" +
	"\aoptions\x18\x02 \x03(\v2 .wildberries.ai.OptionSuggestionR\aoptions\"<\n" +
	"\x10OptionSuggestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"]\n" +
	"\x19GenerateQuestionsResponse\x12@\n" +
	"\tquestions\x18\x01 \x03(\v2\".wildberries.ai.QuestionSuggestionR\tquestions\"1\n" +
	"\x19GenerateAnswerTreeRequest\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\"{\n" +
	"\x0eAnswerTreeNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12$\n" +
	"\x0eparent_node_id\x18\x02 \x01(\tR\fparentNodeId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"R\n" +
	"\x1aGenerateAnswerTreeResponse\x124\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1e.wildberries.ai.AnswerTreeNodeR\x05nodes\"\xae\x01\n" +
	"\x0eGetTextRequest\x12B\n" +
	"\x06params\x18\x01 \x03(\v2*.wildberries.ai.GetTextRequest.ParamsEntryR\x06params\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\x03R\tsegmentId\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\x0fGetTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\xe2\n" +
	"\n" +
	"\tAIService\x12\x90\x02\n" +
	"\x0eGenerateThemes\x12%.wildberries.ai.GenerateThemesRequest\x1a&.wildberries.ai.GenerateThemesResponse\"\xae\x01\x92A\x95\x01\n" +
	"\x02AI\x12#Сгенерировать темы\x1aZГенерирует список тем для использования в акциях*\x0eGenerateThemes\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/ai/themes\x12\xa1\x02\n" +
	"\x10GenerateSegments\x12'.wildberries.ai.GenerateSegmentsRequest\x1a(.wildberries.ai.GenerateSegmentsResponse\"\xb9\x01\x92A\x9e\x01\n" +
	"\x02AI\x12+Сгенерировать сегменты\x1aYГенерирует предложения сегментов на основе темы*\x10GenerateSegments\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/ai/segments\x12\x9d\x02\n" +
	"\x11GenerateQuestions\x12(.wildberries.ai.GenerateQuestionsRequest\x1a).wildberries.ai.GenerateQuestionsResponse\"\xb2\x01\x92A\x96\x01\n" +
	"\x02AI\x12)Сгенерировать вопросы\x1aRГенерирует вопросы для опроса на основе темы*\x11GenerateQuestions\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/ai/questions\x12\xa2\x02\n" +
	"\x12GenerateAnswerTree\x12).wildberries.ai.GenerateAnswerTreeRequest\x1a*.wildberries.ai.GenerateAnswerTreeResponse\"\xb4\x01\x92A\x96\x01\n" +
	"\x02AI\x126Сгенерировать дерево ответов\x1aDГенерирует дерево ответов для опроса*\x12GenerateAnswerTree\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/ai/answer-tree\x12\xd8\x01\n" +
	"\aGetText\x12\x1e.wildberries.ai.GetTextRequest\x1a\x1f.wildberries.ai.GetTextResponse\"\x8b\x01\x92Aq\n" +
	"\x02AI\x12\x1bПолучить текст\x1aEПолучает текст для сегмента или акции*\aGetText\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/ai/get-textB\xda\x01\x92A\xbf\x01\x12\x85\x01\n" +
	"\x0fAI сервис\x12kСервис генерации тем, сегментов, вопросов и дерева ответов2\x051.0.0\x1a\x0elocalhost:7003*\x01\x012\x10application/json:\x10application/jsonZ\x15wildberries/pkg/ai;aib\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_ai_proto_goTypes = []any{
	(*GenerateThemesRequest)(nil),      // 0: wildberries.ai.GenerateThemesRequest
	(*ThemeItem)(nil),                  // 1: wildberries.ai.ThemeItem
	(*GenerateThemesResponse)(nil),     // 2: wildberries.ai.GenerateThemesResponse
	(*GenerateSegmentsRequest)(nil),    // 3: wildberries.ai.GenerateSegmentsRequest
	(*SegmentSuggestion)(nil),          // 4: wildberries.ai.SegmentSuggestion
	(*GenerateSegmentsResponse)(nil),   // 5: wildberries.ai.GenerateSegmentsResponse
	(*GenerateQuestionsRequest)(nil),   // 6: wildberries.ai.GenerateQuestionsRequest
	(*QuestionSuggestion)(nil),         // 7: wildberries.ai.QuestionSuggestion
	(*OptionSuggestion)(nil),           // 8: wildberries.ai.OptionSuggestion
	(*GenerateQuestionsResponse)(nil),  // 9: wildberries.ai.GenerateQuestionsResponse
	(*GenerateAnswerTreeRequest)(nil),  // 10: wildberries.ai.GenerateAnswerTreeRequest
	(*AnswerTreeNode)(nil),             // 11: wildberries.ai.AnswerTreeNode
	(*GenerateAnswerTreeResponse)(nil), // 12: wildberries.ai.GenerateAnswerTreeResponse
	(*GetTextRequest)(nil),             // 13: wildberries.ai.GetTextRequest
	(*GetTextResponse)(nil),            // 14: wildberries.ai.GetTextResponse
	nil,                                // 15: wildberries.ai.GetTextRequest.ParamsEntry
}
var file_ai_proto_depIdxs = []int32{
	1,  // 0: wildberries.ai.GenerateThemesResponse.themes:type_name -> wildberries.ai.ThemeItem
	4,  // 1: wildberries.ai.GenerateSegmentsResponse.segments:type_name -> wildberries.ai.SegmentSuggestion
	8,  // 2: wildberries.ai.QuestionSuggestion.options:type_name -> wildberries.ai.OptionSuggestion
	7,  // 3: wildberries.ai.GenerateQuestionsResponse.questions:type_name -> wildberries.ai.QuestionSuggestion
	11, // 4: wildberries.ai.GenerateAnswerTreeResponse.nodes:type_name -> wildberries.ai.AnswerTreeNode
	15, // 5: wildberries.ai.GetTextRequest.params:type_name -> wildberries.ai.GetTextRequest.ParamsEntry
	0,  // 6: wildberries.ai.AIService.GenerateThemes:input_type -> wildberries.ai.GenerateThemesRequest
	3,  // 7: wildberries.ai.AIService.GenerateSegments:input_type -> wildberries.ai.GenerateSegmentsRequest
	6,  // 8: wildberries.ai.AIService.GenerateQuestions:input_type -> wildberries.ai.GenerateQuestionsRequest
	10, // 9: wildberries.ai.AIService.GenerateAnswerTree:input_type -> wildberries.ai.GenerateAnswerTreeRequest
	13, // 10: wildberries.ai.AIService.GetText:input_type -> wildberries.ai.GetTextRequest
	2,  // 11: wildberries.ai.AIService.GenerateThemes:output_type -> wildberries.ai.GenerateThemesResponse
	5,  // 12: wildberries.ai.AIService.GenerateSegments:output_type -> wildberries.ai.GenerateSegmentsResponse
	9,  // 13: wildberries.ai.AIService.GenerateQuestions:output_type -> wildberries.ai.GenerateQuestionsResponse
	12, // 14: wildberries.ai.AIService.GenerateAnswerTree:output_type -> wildberries.ai.GenerateAnswerTreeResponse
	14, // 15: wildberries.ai.AIService.GetText:output_type -> wildberries.ai.GetTextResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
