// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIService_GenerateThemes_FullMethodName     = "/wildberries.ai.AIService/GenerateThemes"
	AIService_GenerateSegments_FullMethodName   = "/wildberries.ai.AIService/GenerateSegments"
	AIService_GenerateQuestions_FullMethodName  = "/wildberries.ai.AIService/GenerateQuestions"
	AIService_GenerateAnswerTree_FullMethodName = "/wildberries.ai.AIService/GenerateAnswerTree"
	AIService_GetText_FullMethodName            = "/wildberries.ai.AIService/GetText"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	GenerateThemes(ctx context.Context, in *GenerateThemesRequest, opts ...grpc.CallOption) (*GenerateThemesResponse, error)
	GenerateSegments(ctx context.Context, in *GenerateSegmentsRequest, opts ...grpc.CallOption) (*GenerateSegmentsResponse, error)
	GenerateQuestions(ctx context.Context, in *GenerateQuestionsRequest, opts ...grpc.CallOption) (*GenerateQuestionsResponse, error)
	GenerateAnswerTree(ctx context.Context, in *GenerateAnswerTreeRequest, opts ...grpc.CallOption) (*GenerateAnswerTreeResponse, error)
	GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) GenerateThemes(ctx context.Context, in *GenerateThemesRequest, opts ...grpc.CallOption) (*GenerateThemesResponse, error) {
	out := new(GenerateThemesResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateThemes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateSegments(ctx context.Context, in *GenerateSegmentsRequest, opts ...grpc.CallOption) (*GenerateSegmentsResponse, error) {
	out := new(GenerateSegmentsResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateSegments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateQuestions(ctx context.Context, in *GenerateQuestionsRequest, opts ...grpc.CallOption) (*GenerateQuestionsResponse, error) {
	out := new(GenerateQuestionsResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateQuestions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateAnswerTree(ctx context.Context, in *GenerateAnswerTreeRequest, opts ...grpc.CallOption) (*GenerateAnswerTreeResponse, error) {
	out := new(GenerateAnswerTreeResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateAnswerTree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error) {
	out := new(GetTextResponse)
	err := c.cc.Invoke(ctx, AIService_GetText_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility
type AIServiceServer interface {
	GenerateThemes(context.Context, *GenerateThemesRequest) (*GenerateThemesResponse, error)
	GenerateSegments(context.Context, *GenerateSegmentsRequest) (*GenerateSegmentsResponse, error)
	GenerateQuestions(context.Context, *GenerateQuestionsRequest) (*GenerateQuestionsResponse, error)
	GenerateAnswerTree(context.Context, *GenerateAnswerTreeRequest) (*GenerateAnswerTreeResponse, error)
	GetText(context.Context, *GetTextRequest) (*GetTextResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIServiceServer struct {
}

func (UnimplementedAIServiceServer) GenerateThemes(context.Context, *GenerateThemesRequest) (*GenerateThemesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateThemes not implemented")
}
func (UnimplementedAIServiceServer) GenerateSegments(context.Context, *GenerateSegmentsRequest) (*GenerateSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSegments not implemented")
}
func (UnimplementedAIServiceServer) GenerateQuestions(context.Context, *GenerateQuestionsRequest) (*GenerateQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQuestions not implemented")
}
func (UnimplementedAIServiceServer) GenerateAnswerTree(context.Context, *GenerateAnswerTreeRequest) (*GenerateAnswerTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAnswerTree not implemented")
}
func (UnimplementedAIServiceServer) GetText(context.Context, *GetTextRequest) (*GetTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetText not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_GenerateThemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateThemesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateThemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateThemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateThemes(ctx, req.(*GenerateThemesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateSegments(ctx, req.(*GenerateSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateQuestions(ctx, req.(*GenerateQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateAnswerTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAnswerTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateAnswerTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateAnswerTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateAnswerTree(ctx, req.(*GenerateAnswerTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetText(ctx, req.(*GetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateThemes",
			Handler:    _AIService_GenerateThemes_Handler,
		},
		{
			MethodName: "GenerateSegments",
			Handler:    _AIService_GenerateSegments_Handler,
		},
		{
			MethodName: "GenerateQuestions",
			Handler:    _AIService_GenerateQuestions_Handler,
		},
		{
			MethodName: "GenerateAnswerTree",
			Handler:    _AIService_GenerateAnswerTree_Handler,
		},
		{
			MethodName: "GetText",
			Handler:    _AIService_GetText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
