// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: seller.proto

package seller

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- GET /products/list-by — список продуктов селлера ---
type ListProductsByRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` // optional filter
	SellerId      int64                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsByRequest) Reset() {
	*x = ListProductsByRequest{}
	mi := &file_seller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsByRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsByRequest) ProtoMessage() {}

func (x *ListProductsByRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsByRequest.ProtoReflect.Descriptor instead.
func (*ListProductsByRequest) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductsByRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListProductsByRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *ListProductsByRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsByRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ProductListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NmId          int64                  `protobuf:"varint,2,opt,name=nm_id,json=nmId,proto3" json:"nm_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Discount      int32                  `protobuf:"varint,7,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListItem) Reset() {
	*x = ProductListItem{}
	mi := &file_seller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListItem) ProtoMessage() {}

func (x *ProductListItem) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListItem.ProtoReflect.Descriptor instead.
func (*ProductListItem) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{1}
}

func (x *ProductListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductListItem) GetNmId() int64 {
	if x != nil {
		return x.NmId
	}
	return 0
}

func (x *ProductListItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProductListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductListItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductListItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductListItem) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

type ListProductsByResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductListItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsByResponse) Reset() {
	*x = ListProductsByResponse{}
	mi := &file_seller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsByResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsByResponse) ProtoMessage() {}

func (x *ListProductsByResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsByResponse.ProtoReflect.Descriptor instead.
func (*ListProductsByResponse) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsByResponse) GetItems() []*ProductListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProductsByResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsByResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsByResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// --- GET /seller/actions — доступные акции для селлера ---
type GetSellerActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      int64                  `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerActionsRequest) Reset() {
	*x = GetSellerActionsRequest{}
	mi := &file_seller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerActionsRequest) ProtoMessage() {}

func (x *GetSellerActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerActionsRequest.ProtoReflect.Descriptor instead.
func (*GetSellerActionsRequest) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{3}
}

func (x *GetSellerActionsRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

type SellerActionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DateFrom      string                 `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	CategoryHint  string                 `protobuf:"bytes,6,opt,name=category_hint,json=categoryHint,proto3" json:"category_hint,omitempty"`
	Theme         string                 `protobuf:"bytes,7,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerActionSummary) Reset() {
	*x = SellerActionSummary{}
	mi := &file_seller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerActionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerActionSummary) ProtoMessage() {}

func (x *SellerActionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerActionSummary.ProtoReflect.Descriptor instead.
func (*SellerActionSummary) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{4}
}

func (x *SellerActionSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SellerActionSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SellerActionSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SellerActionSummary) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *SellerActionSummary) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *SellerActionSummary) GetCategoryHint() string {
	if x != nil {
		return x.CategoryHint
	}
	return ""
}

func (x *SellerActionSummary) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type GetSellerActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*SellerActionSummary `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerActionsResponse) Reset() {
	*x = GetSellerActionsResponse{}
	mi := &file_seller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerActionsResponse) ProtoMessage() {}

func (x *GetSellerActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerActionsResponse.ProtoReflect.Descriptor instead.
func (*GetSellerActionsResponse) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{5}
}

func (x *GetSellerActionsResponse) GetActions() []*SellerActionSummary {
	if x != nil {
		return x.Actions
	}
	return nil
}

// --- GET /seller/bets/list — ставки/заявки селлера ---
type GetSellerBetsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromotionId   int64                  `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                               // optional
	SellerId      int64                  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerBetsListRequest) Reset() {
	*x = GetSellerBetsListRequest{}
	mi := &file_seller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerBetsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerBetsListRequest) ProtoMessage() {}

func (x *GetSellerBetsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerBetsListRequest.ProtoReflect.Descriptor instead.
func (*GetSellerBetsListRequest) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{6}
}

func (x *GetSellerBetsListRequest) GetPromotionId() int64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *GetSellerBetsListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSellerBetsListRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

type SellerBetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // slot/bet/application id
	PromotionId   int64                  `protobuf:"varint,2,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	SegmentId     int64                  `protobuf:"varint,3,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	SlotId        int64                  `protobuf:"varint,4,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Bet           int64                  `protobuf:"varint,5,opt,name=bet,proto3" json:"bet,omitempty"`      // для аукциона
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`  // для фиксированного
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // available, pending, moderation, occupied, rejected
	ProductName   string                 `protobuf:"bytes,8,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerBetItem) Reset() {
	*x = SellerBetItem{}
	mi := &file_seller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerBetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerBetItem) ProtoMessage() {}

func (x *SellerBetItem) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerBetItem.ProtoReflect.Descriptor instead.
func (*SellerBetItem) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{7}
}

func (x *SellerBetItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SellerBetItem) GetPromotionId() int64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *SellerBetItem) GetSegmentId() int64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *SellerBetItem) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SellerBetItem) GetBet() int64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SellerBetItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SellerBetItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SellerBetItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type GetSellerBetsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SellerBetItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellerBetsListResponse) Reset() {
	*x = GetSellerBetsListResponse{}
	mi := &file_seller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellerBetsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerBetsListResponse) ProtoMessage() {}

func (x *GetSellerBetsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerBetsListResponse.ProtoReflect.Descriptor instead.
func (*GetSellerBetsListResponse) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{8}
}

func (x *GetSellerBetsListResponse) GetItems() []*SellerBetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// --- POST /seller/bets/make ---
type MakeBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      int64                  `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	SlotId        int64                  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`  // для аукциона — сумма ставки
	Product       *ProductForSlot        `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"` // для фиксированной цены
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBetRequest) Reset() {
	*x = MakeBetRequest{}
	mi := &file_seller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBetRequest) ProtoMessage() {}

func (x *MakeBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBetRequest.ProtoReflect.Descriptor instead.
func (*MakeBetRequest) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{9}
}

func (x *MakeBetRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *MakeBetRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *MakeBetRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MakeBetRequest) GetProduct() *ProductForSlot {
	if x != nil {
		return x.Product
	}
	return nil
}

type ProductForSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Discount      int32                  `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductForSlot) Reset() {
	*x = ProductForSlot{}
	mi := &file_seller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductForSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductForSlot) ProtoMessage() {}

func (x *ProductForSlot) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductForSlot.ProtoReflect.Descriptor instead.
func (*ProductForSlot) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{10}
}

func (x *ProductForSlot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductForSlot) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductForSlot) GetDiscount() int32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *ProductForSlot) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type MakeBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBetResponse) Reset() {
	*x = MakeBetResponse{}
	mi := &file_seller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBetResponse) ProtoMessage() {}

func (x *MakeBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBetResponse.ProtoReflect.Descriptor instead.
func (*MakeBetResponse) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{11}
}

func (x *MakeBetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MakeBetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- POST /seller/bets/remove ---
type RemoveBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SellerId      int64                  `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBetRequest) Reset() {
	*x = RemoveBetRequest{}
	mi := &file_seller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBetRequest) ProtoMessage() {}

func (x *RemoveBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBetRequest.ProtoReflect.Descriptor instead.
func (*RemoveBetRequest) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveBetRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *RemoveBetRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

type RemoveBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBetResponse) Reset() {
	*x = RemoveBetResponse{}
	mi := &file_seller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBetResponse) ProtoMessage() {}

func (x *RemoveBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBetResponse.ProtoReflect.Descriptor instead.
func (*RemoveBetResponse) Descriptor() ([]byte, []int) {
	return file_seller_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveBetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_seller_proto protoreflect.FileDescriptor

const file_seller_proto_rawDesc = "" +
	"\n" +
	"\fseller.proto\x12\x12wildberries.seller\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x84\x01\n" +
	"\x15ListProductsByRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x03R\bsellerId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"\xb7\x01\n" +
	"\x0fProductListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x13\n" +
	"\x05nm_id\x18\x02 \x01(\x03R\x04nmId\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x1a\n" +
	"\bdiscount\x18\a \x01(\x05R\bdiscount\"\x98\x01\n" +
	"\x16ListProductsByResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.wildberries.seller.ProductListItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"6\n" +
	"\x17GetSellerActionsRequest\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\x03R\bsellerId\"\xc2\x01\n" +
	"\x13SellerActionSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tdate_from\x18\x04 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x05 \x01(\tR\x06dateTo\x12#\n" +
	"\rcategory_hint\x18\x06 \x01(\tR\fcategoryHint\x12\x14\n" +
	"\x05theme\x18\a \x01(\tR\x05theme\"]\n" +
	"\x18GetSellerActionsResponse\x12A\n" +
	"\aactions\x18\x01 \x03(\v2'.wildberries.seller.SellerActionSummaryR\aactions\"r\n" +
	"\x18GetSellerBetsListRequest\x12!\n" +
	"\fpromotion_id\x18\x01 \x01(\x03R\vpromotionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\"\xdd\x01\n" +
	"\rSellerBetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fpromotion_id\x18\x02 \x01(\x03R\vpromotionId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x03 \x01(\x03R\tsegmentId\x12\x17\n" +
	"\aslot_id\x18\x04 \x01(\x03R\x06slotId\x12\x10\n" +
	"\x03bet\x18\x05 \x01(\x03R\x03bet\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fproduct_name\x18\b \x01(\tR\vproductName\"T\n" +
	"\x19GetSellerBetsListResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.wildberries.seller.SellerBetItemR\x05items\"\x9c\x01\n" +
	"\x0eMakeBetRequest\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\x03R\bsellerId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x03R\x06slotId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12<\n" +
	"\aproduct\x18\x04 \x01(\v2\".wildberries.seller.ProductForSlotR\aproduct\"l\n" +
	"\x0eProductForSlot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x1a\n" +
	"\bdiscount\x18\x03 \x01(\x05R\bdiscount\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"E\n" +
	"\x0fMakeBetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x10RemoveBetRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x03R\bsellerId\"-\n" +
	"\x11RemoveBetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe7\x02\n" +
	"\x14SellerProductService\x12\xce\x02\n" +
	"\x0eListProductsBy\x12).wildberries.seller.ListProductsByRequest\x1a*.wildberries.seller.ListProductsByResponse\"\xe4\x01\x92A\xc7\x01\n" +
	"\bProducts\x12?Получить список продуктов селлера\x1ajПолучает список продуктов селлера по заданным параметрам*\x0eListProductsBy\x82\xd3\xe4\x93\x02\x13\x12\x11/products/list-by2\xd8\x02\n" +
	"\x14SellerActionsService\x12\xbf\x02\n" +
	"\x10GetSellerActions\x12+.wildberries.seller.GetSellerActionsRequest\x1a,.wildberries.seller.GetSellerActionsResponse\"\xcf\x01\x92A\xb4\x01\n" +
	"\aActions\x12DПолучить доступные акции для селлера\x1aQПолучает список доступных акций для селлера*\x10GetSellerActions\x82\xd3\xe4\x93\x02\x11\x12\x0f/seller/actions2\x9c\x06\n" +
	"\x11SellerBetsService\x12\xca\x02\n" +
	"\x11GetSellerBetsList\x12,.wildberries.seller.GetSellerBetsListRequest\x1a-.wildberries.seller.GetSellerBetsListResponse\"\xd7\x01\x92A\xba\x01\n" +
	"\x04Bets\x129Получить список ставок селлера\x1adПолучает список ставок селлера по заданным параметрам*\x11GetSellerBetsList\x82\xd3\xe4\x93\x02\x13\x12\x11/seller/bets/list\x12\xd6\x01\n" +
	"\aMakeBet\x12\".wildberries.seller.MakeBetRequest\x1a#.wildberries.seller.MakeBetResponse\"\x81\x01\x92Ab\n" +
	"\x04Bets\x12\x1bСделать ставку\x1a4Создает новую ставку на слот*\aMakeBet\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/seller/bets/make\x12\xe0\x01\n" +
	"\tRemoveBet\x12$.wildberries.seller.RemoveBetRequest\x1a%.wildberries.seller.RemoveBetResponse\"\x85\x01\x92Ad\n" +
	"\x04Bets\x12\x1bУдалить ставку\x1a4Удаляет существующую ставку*\tRemoveBet\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/seller/bets/removeB\xbb\x01\x92A\x98\x01\x12_\n" +
	"\x13Seller сервис\x12AСервис селлера для работы с акциями2\x051.0.0\x1a\x0elocalhost:7004*\x01\x012\x10application/json:\x10application/jsonZ\x1dwildberries/pkg/seller;sellerb\x06proto3"

var (
	file_seller_proto_rawDescOnce sync.Once
	file_seller_proto_rawDescData []byte
)

func file_seller_proto_rawDescGZIP() []byte {
	file_seller_proto_rawDescOnce.Do(func() {
		file_seller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seller_proto_rawDesc), len(file_seller_proto_rawDesc)))
	})
	return file_seller_proto_rawDescData
}

var file_seller_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_seller_proto_goTypes = []any{
	(*ListProductsByRequest)(nil),     // 0: wildberries.seller.ListProductsByRequest
	(*ProductListItem)(nil),           // 1: wildberries.seller.ProductListItem
	(*ListProductsByResponse)(nil),    // 2: wildberries.seller.ListProductsByResponse
	(*GetSellerActionsRequest)(nil),   // 3: wildberries.seller.GetSellerActionsRequest
	(*SellerActionSummary)(nil),       // 4: wildberries.seller.SellerActionSummary
	(*GetSellerActionsResponse)(nil),  // 5: wildberries.seller.GetSellerActionsResponse
	(*GetSellerBetsListRequest)(nil),  // 6: wildberries.seller.GetSellerBetsListRequest
	(*SellerBetItem)(nil),             // 7: wildberries.seller.SellerBetItem
	(*GetSellerBetsListResponse)(nil), // 8: wildberries.seller.GetSellerBetsListResponse
	(*MakeBetRequest)(nil),            // 9: wildberries.seller.MakeBetRequest
	(*ProductForSlot)(nil),            // 10: wildberries.seller.ProductForSlot
	(*MakeBetResponse)(nil),           // 11: wildberries.seller.MakeBetResponse
	(*RemoveBetRequest)(nil),          // 12: wildberries.seller.RemoveBetRequest
	(*RemoveBetResponse)(nil),         // 13: wildberries.seller.RemoveBetResponse
}
var file_seller_proto_depIdxs = []int32{
	1,  // 0: wildberries.seller.ListProductsByResponse.items:type_name -> wildberries.seller.ProductListItem
	4,  // 1: wildberries.seller.GetSellerActionsResponse.actions:type_name -> wildberries.seller.SellerActionSummary
	7,  // 2: wildberries.seller.GetSellerBetsListResponse.items:type_name -> wildberries.seller.SellerBetItem
	10, // 3: wildberries.seller.MakeBetRequest.product:type_name -> wildberries.seller.ProductForSlot
	0,  // 4: wildberries.seller.SellerProductService.ListProductsBy:input_type -> wildberries.seller.ListProductsByRequest
	3,  // 5: wildberries.seller.SellerActionsService.GetSellerActions:input_type -> wildberries.seller.GetSellerActionsRequest
	6,  // 6: wildberries.seller.SellerBetsService.GetSellerBetsList:input_type -> wildberries.seller.GetSellerBetsListRequest
	9,  // 7: wildberries.seller.SellerBetsService.MakeBet:input_type -> wildberries.seller.MakeBetRequest
	12, // 8: wildberries.seller.SellerBetsService.RemoveBet:input_type -> wildberries.seller.RemoveBetRequest
	2,  // 9: wildberries.seller.SellerProductService.ListProductsBy:output_type -> wildberries.seller.ListProductsByResponse
	5,  // 10: wildberries.seller.SellerActionsService.GetSellerActions:output_type -> wildberries.seller.GetSellerActionsResponse
	8,  // 11: wildberries.seller.SellerBetsService.GetSellerBetsList:output_type -> wildberries.seller.GetSellerBetsListResponse
	11, // 12: wildberries.seller.SellerBetsService.MakeBet:output_type -> wildberries.seller.MakeBetResponse
	13, // 13: wildberries.seller.SellerBetsService.RemoveBet:output_type -> wildberries.seller.RemoveBetResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_seller_proto_init() }
func file_seller_proto_init() {
	if File_seller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seller_proto_rawDesc), len(file_seller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_seller_proto_goTypes,
		DependencyIndexes: file_seller_proto_depIdxs,
		MessageInfos:      file_seller_proto_msgTypes,
	}.Build()
	File_seller_proto = out.File
	file_seller_proto_goTypes = nil
	file_seller_proto_depIdxs = nil
}
