// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: seller.proto

package seller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SellerProductService_ListProductsBy_FullMethodName = "/wildberries.seller.SellerProductService/ListProductsBy"
)

// SellerProductServiceClient is the client API for SellerProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerProductServiceClient interface {
	ListProductsBy(ctx context.Context, in *ListProductsByRequest, opts ...grpc.CallOption) (*ListProductsByResponse, error)
}

type sellerProductServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerProductServiceClient(cc grpc.ClientConnInterface) SellerProductServiceClient {
	return &sellerProductServiceClient{cc}
}

func (c *sellerProductServiceClient) ListProductsBy(ctx context.Context, in *ListProductsByRequest, opts ...grpc.CallOption) (*ListProductsByResponse, error) {
	out := new(ListProductsByResponse)
	err := c.cc.Invoke(ctx, SellerProductService_ListProductsBy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerProductServiceServer is the server API for SellerProductService service.
// All implementations must embed UnimplementedSellerProductServiceServer
// for forward compatibility
type SellerProductServiceServer interface {
	ListProductsBy(context.Context, *ListProductsByRequest) (*ListProductsByResponse, error)
	mustEmbedUnimplementedSellerProductServiceServer()
}

// UnimplementedSellerProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSellerProductServiceServer struct {
}

func (UnimplementedSellerProductServiceServer) ListProductsBy(context.Context, *ListProductsByRequest) (*ListProductsByResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductsBy not implemented")
}
func (UnimplementedSellerProductServiceServer) mustEmbedUnimplementedSellerProductServiceServer() {}

// UnsafeSellerProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerProductServiceServer will
// result in compilation errors.
type UnsafeSellerProductServiceServer interface {
	mustEmbedUnimplementedSellerProductServiceServer()
}

func RegisterSellerProductServiceServer(s grpc.ServiceRegistrar, srv SellerProductServiceServer) {
	s.RegisterService(&SellerProductService_ServiceDesc, srv)
}

func _SellerProductService_ListProductsBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerProductServiceServer).ListProductsBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerProductService_ListProductsBy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerProductServiceServer).ListProductsBy(ctx, req.(*ListProductsByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerProductService_ServiceDesc is the grpc.ServiceDesc for SellerProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.seller.SellerProductService",
	HandlerType: (*SellerProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductsBy",
			Handler:    _SellerProductService_ListProductsBy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller.proto",
}

const (
	SellerActionsService_GetSellerActions_FullMethodName = "/wildberries.seller.SellerActionsService/GetSellerActions"
)

// SellerActionsServiceClient is the client API for SellerActionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerActionsServiceClient interface {
	GetSellerActions(ctx context.Context, in *GetSellerActionsRequest, opts ...grpc.CallOption) (*GetSellerActionsResponse, error)
}

type sellerActionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerActionsServiceClient(cc grpc.ClientConnInterface) SellerActionsServiceClient {
	return &sellerActionsServiceClient{cc}
}

func (c *sellerActionsServiceClient) GetSellerActions(ctx context.Context, in *GetSellerActionsRequest, opts ...grpc.CallOption) (*GetSellerActionsResponse, error) {
	out := new(GetSellerActionsResponse)
	err := c.cc.Invoke(ctx, SellerActionsService_GetSellerActions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerActionsServiceServer is the server API for SellerActionsService service.
// All implementations must embed UnimplementedSellerActionsServiceServer
// for forward compatibility
type SellerActionsServiceServer interface {
	GetSellerActions(context.Context, *GetSellerActionsRequest) (*GetSellerActionsResponse, error)
	mustEmbedUnimplementedSellerActionsServiceServer()
}

// UnimplementedSellerActionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSellerActionsServiceServer struct {
}

func (UnimplementedSellerActionsServiceServer) GetSellerActions(context.Context, *GetSellerActionsRequest) (*GetSellerActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerActions not implemented")
}
func (UnimplementedSellerActionsServiceServer) mustEmbedUnimplementedSellerActionsServiceServer() {}

// UnsafeSellerActionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerActionsServiceServer will
// result in compilation errors.
type UnsafeSellerActionsServiceServer interface {
	mustEmbedUnimplementedSellerActionsServiceServer()
}

func RegisterSellerActionsServiceServer(s grpc.ServiceRegistrar, srv SellerActionsServiceServer) {
	s.RegisterService(&SellerActionsService_ServiceDesc, srv)
}

func _SellerActionsService_GetSellerActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerActionsServiceServer).GetSellerActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerActionsService_GetSellerActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerActionsServiceServer).GetSellerActions(ctx, req.(*GetSellerActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerActionsService_ServiceDesc is the grpc.ServiceDesc for SellerActionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerActionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.seller.SellerActionsService",
	HandlerType: (*SellerActionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSellerActions",
			Handler:    _SellerActionsService_GetSellerActions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller.proto",
}

const (
	SellerBetsService_GetSellerBetsList_FullMethodName = "/wildberries.seller.SellerBetsService/GetSellerBetsList"
	SellerBetsService_MakeBet_FullMethodName           = "/wildberries.seller.SellerBetsService/MakeBet"
	SellerBetsService_RemoveBet_FullMethodName         = "/wildberries.seller.SellerBetsService/RemoveBet"
)

// SellerBetsServiceClient is the client API for SellerBetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerBetsServiceClient interface {
	GetSellerBetsList(ctx context.Context, in *GetSellerBetsListRequest, opts ...grpc.CallOption) (*GetSellerBetsListResponse, error)
	MakeBet(ctx context.Context, in *MakeBetRequest, opts ...grpc.CallOption) (*MakeBetResponse, error)
	RemoveBet(ctx context.Context, in *RemoveBetRequest, opts ...grpc.CallOption) (*RemoveBetResponse, error)
}

type sellerBetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerBetsServiceClient(cc grpc.ClientConnInterface) SellerBetsServiceClient {
	return &sellerBetsServiceClient{cc}
}

func (c *sellerBetsServiceClient) GetSellerBetsList(ctx context.Context, in *GetSellerBetsListRequest, opts ...grpc.CallOption) (*GetSellerBetsListResponse, error) {
	out := new(GetSellerBetsListResponse)
	err := c.cc.Invoke(ctx, SellerBetsService_GetSellerBetsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerBetsServiceClient) MakeBet(ctx context.Context, in *MakeBetRequest, opts ...grpc.CallOption) (*MakeBetResponse, error) {
	out := new(MakeBetResponse)
	err := c.cc.Invoke(ctx, SellerBetsService_MakeBet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerBetsServiceClient) RemoveBet(ctx context.Context, in *RemoveBetRequest, opts ...grpc.CallOption) (*RemoveBetResponse, error) {
	out := new(RemoveBetResponse)
	err := c.cc.Invoke(ctx, SellerBetsService_RemoveBet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerBetsServiceServer is the server API for SellerBetsService service.
// All implementations must embed UnimplementedSellerBetsServiceServer
// for forward compatibility
type SellerBetsServiceServer interface {
	GetSellerBetsList(context.Context, *GetSellerBetsListRequest) (*GetSellerBetsListResponse, error)
	MakeBet(context.Context, *MakeBetRequest) (*MakeBetResponse, error)
	RemoveBet(context.Context, *RemoveBetRequest) (*RemoveBetResponse, error)
	mustEmbedUnimplementedSellerBetsServiceServer()
}

// UnimplementedSellerBetsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSellerBetsServiceServer struct {
}

func (UnimplementedSellerBetsServiceServer) GetSellerBetsList(context.Context, *GetSellerBetsListRequest) (*GetSellerBetsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerBetsList not implemented")
}
func (UnimplementedSellerBetsServiceServer) MakeBet(context.Context, *MakeBetRequest) (*MakeBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeBet not implemented")
}
func (UnimplementedSellerBetsServiceServer) RemoveBet(context.Context, *RemoveBetRequest) (*RemoveBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBet not implemented")
}
func (UnimplementedSellerBetsServiceServer) mustEmbedUnimplementedSellerBetsServiceServer() {}

// UnsafeSellerBetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerBetsServiceServer will
// result in compilation errors.
type UnsafeSellerBetsServiceServer interface {
	mustEmbedUnimplementedSellerBetsServiceServer()
}

func RegisterSellerBetsServiceServer(s grpc.ServiceRegistrar, srv SellerBetsServiceServer) {
	s.RegisterService(&SellerBetsService_ServiceDesc, srv)
}

func _SellerBetsService_GetSellerBetsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerBetsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerBetsServiceServer).GetSellerBetsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerBetsService_GetSellerBetsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerBetsServiceServer).GetSellerBetsList(ctx, req.(*GetSellerBetsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerBetsService_MakeBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerBetsServiceServer).MakeBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerBetsService_MakeBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerBetsServiceServer).MakeBet(ctx, req.(*MakeBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerBetsService_RemoveBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerBetsServiceServer).RemoveBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SellerBetsService_RemoveBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerBetsServiceServer).RemoveBet(ctx, req.(*RemoveBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SellerBetsService_ServiceDesc is the grpc.ServiceDesc for SellerBetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SellerBetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.seller.SellerBetsService",
	HandlerType: (*SellerBetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSellerBetsList",
			Handler:    _SellerBetsService_GetSellerBetsList_Handler,
		},
		{
			MethodName: "MakeBet",
			Handler:    _SellerBetsService_MakeBet_Handler,
		},
		{
			MethodName: "RemoveBet",
			Handler:    _SellerBetsService_RemoveBet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller.proto",
}
