// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PromotionAdminService_CreatePromotion_FullMethodName = "/wildberries.admin.PromotionAdminService/CreatePromotion"
	PromotionAdminService_GetPromotion_FullMethodName    = "/wildberries.admin.PromotionAdminService/GetPromotion"
	PromotionAdminService_UpdatePromotion_FullMethodName = "/wildberries.admin.PromotionAdminService/UpdatePromotion"
	PromotionAdminService_DeletePromotion_FullMethodName = "/wildberries.admin.PromotionAdminService/DeletePromotion"
	PromotionAdminService_SetFixedPrices_FullMethodName  = "/wildberries.admin.PromotionAdminService/SetFixedPrices"
	PromotionAdminService_ChangeStatus_FullMethodName    = "/wildberries.admin.PromotionAdminService/ChangeStatus"
	PromotionAdminService_SetSlotProduct_FullMethodName  = "/wildberries.admin.PromotionAdminService/SetSlotProduct"
)

// PromotionAdminServiceClient is the client API for PromotionAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromotionAdminServiceClient interface {
	CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*CreatePromotionResponse, error)
	GetPromotion(ctx context.Context, in *GetPromotionRequest, opts ...grpc.CallOption) (*GetPromotionResponse, error)
	UpdatePromotion(ctx context.Context, in *UpdatePromotionRequest, opts ...grpc.CallOption) (*UpdatePromotionResponse, error)
	DeletePromotion(ctx context.Context, in *DeletePromotionRequest, opts ...grpc.CallOption) (*DeletePromotionResponse, error)
	SetFixedPrices(ctx context.Context, in *SetFixedPricesRequest, opts ...grpc.CallOption) (*SetFixedPricesResponse, error)
	ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error)
	SetSlotProduct(ctx context.Context, in *SetSlotProductRequest, opts ...grpc.CallOption) (*SetSlotProductResponse, error)
}

type promotionAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionAdminServiceClient(cc grpc.ClientConnInterface) PromotionAdminServiceClient {
	return &promotionAdminServiceClient{cc}
}

func (c *promotionAdminServiceClient) CreatePromotion(ctx context.Context, in *CreatePromotionRequest, opts ...grpc.CallOption) (*CreatePromotionResponse, error) {
	out := new(CreatePromotionResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_CreatePromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAdminServiceClient) GetPromotion(ctx context.Context, in *GetPromotionRequest, opts ...grpc.CallOption) (*GetPromotionResponse, error) {
	out := new(GetPromotionResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_GetPromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAdminServiceClient) UpdatePromotion(ctx context.Context, in *UpdatePromotionRequest, opts ...grpc.CallOption) (*UpdatePromotionResponse, error) {
	out := new(UpdatePromotionResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_UpdatePromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAdminServiceClient) DeletePromotion(ctx context.Context, in *DeletePromotionRequest, opts ...grpc.CallOption) (*DeletePromotionResponse, error) {
	out := new(DeletePromotionResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_DeletePromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAdminServiceClient) SetFixedPrices(ctx context.Context, in *SetFixedPricesRequest, opts ...grpc.CallOption) (*SetFixedPricesResponse, error) {
	out := new(SetFixedPricesResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_SetFixedPrices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAdminServiceClient) ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error) {
	out := new(ChangeStatusResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_ChangeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionAdminServiceClient) SetSlotProduct(ctx context.Context, in *SetSlotProductRequest, opts ...grpc.CallOption) (*SetSlotProductResponse, error) {
	out := new(SetSlotProductResponse)
	err := c.cc.Invoke(ctx, PromotionAdminService_SetSlotProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionAdminServiceServer is the server API for PromotionAdminService service.
// All implementations must embed UnimplementedPromotionAdminServiceServer
// for forward compatibility
type PromotionAdminServiceServer interface {
	CreatePromotion(context.Context, *CreatePromotionRequest) (*CreatePromotionResponse, error)
	GetPromotion(context.Context, *GetPromotionRequest) (*GetPromotionResponse, error)
	UpdatePromotion(context.Context, *UpdatePromotionRequest) (*UpdatePromotionResponse, error)
	DeletePromotion(context.Context, *DeletePromotionRequest) (*DeletePromotionResponse, error)
	SetFixedPrices(context.Context, *SetFixedPricesRequest) (*SetFixedPricesResponse, error)
	ChangeStatus(context.Context, *ChangeStatusRequest) (*ChangeStatusResponse, error)
	SetSlotProduct(context.Context, *SetSlotProductRequest) (*SetSlotProductResponse, error)
	mustEmbedUnimplementedPromotionAdminServiceServer()
}

// UnimplementedPromotionAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPromotionAdminServiceServer struct {
}

func (UnimplementedPromotionAdminServiceServer) CreatePromotion(context.Context, *CreatePromotionRequest) (*CreatePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromotion not implemented")
}
func (UnimplementedPromotionAdminServiceServer) GetPromotion(context.Context, *GetPromotionRequest) (*GetPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromotion not implemented")
}
func (UnimplementedPromotionAdminServiceServer) UpdatePromotion(context.Context, *UpdatePromotionRequest) (*UpdatePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromotion not implemented")
}
func (UnimplementedPromotionAdminServiceServer) DeletePromotion(context.Context, *DeletePromotionRequest) (*DeletePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePromotion not implemented")
}
func (UnimplementedPromotionAdminServiceServer) SetFixedPrices(context.Context, *SetFixedPricesRequest) (*SetFixedPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFixedPrices not implemented")
}
func (UnimplementedPromotionAdminServiceServer) ChangeStatus(context.Context, *ChangeStatusRequest) (*ChangeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeStatus not implemented")
}
func (UnimplementedPromotionAdminServiceServer) SetSlotProduct(context.Context, *SetSlotProductRequest) (*SetSlotProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSlotProduct not implemented")
}
func (UnimplementedPromotionAdminServiceServer) mustEmbedUnimplementedPromotionAdminServiceServer() {}

// UnsafePromotionAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionAdminServiceServer will
// result in compilation errors.
type UnsafePromotionAdminServiceServer interface {
	mustEmbedUnimplementedPromotionAdminServiceServer()
}

func RegisterPromotionAdminServiceServer(s grpc.ServiceRegistrar, srv PromotionAdminServiceServer) {
	s.RegisterService(&PromotionAdminService_ServiceDesc, srv)
}

func _PromotionAdminService_CreatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).CreatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_CreatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).CreatePromotion(ctx, req.(*CreatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAdminService_GetPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).GetPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_GetPromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).GetPromotion(ctx, req.(*GetPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAdminService_UpdatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).UpdatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_UpdatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).UpdatePromotion(ctx, req.(*UpdatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAdminService_DeletePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).DeletePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_DeletePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).DeletePromotion(ctx, req.(*DeletePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAdminService_SetFixedPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFixedPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).SetFixedPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_SetFixedPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).SetFixedPrices(ctx, req.(*SetFixedPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAdminService_ChangeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).ChangeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_ChangeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).ChangeStatus(ctx, req.(*ChangeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionAdminService_SetSlotProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSlotProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionAdminServiceServer).SetSlotProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionAdminService_SetSlotProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionAdminServiceServer).SetSlotProduct(ctx, req.(*SetSlotProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionAdminService_ServiceDesc is the grpc.ServiceDesc for PromotionAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.admin.PromotionAdminService",
	HandlerType: (*PromotionAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePromotion",
			Handler:    _PromotionAdminService_CreatePromotion_Handler,
		},
		{
			MethodName: "GetPromotion",
			Handler:    _PromotionAdminService_GetPromotion_Handler,
		},
		{
			MethodName: "UpdatePromotion",
			Handler:    _PromotionAdminService_UpdatePromotion_Handler,
		},
		{
			MethodName: "DeletePromotion",
			Handler:    _PromotionAdminService_DeletePromotion_Handler,
		},
		{
			MethodName: "SetFixedPrices",
			Handler:    _PromotionAdminService_SetFixedPrices_Handler,
		},
		{
			MethodName: "ChangeStatus",
			Handler:    _PromotionAdminService_ChangeStatus_Handler,
		},
		{
			MethodName: "SetSlotProduct",
			Handler:    _PromotionAdminService_SetSlotProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}

const (
	SegmentAdminService_GenerateSegments_FullMethodName         = "/wildberries.admin.SegmentAdminService/GenerateSegments"
	SegmentAdminService_CreateSegment_FullMethodName            = "/wildberries.admin.SegmentAdminService/CreateSegment"
	SegmentAdminService_UpdateSegment_FullMethodName            = "/wildberries.admin.SegmentAdminService/UpdateSegment"
	SegmentAdminService_DeleteSegment_FullMethodName            = "/wildberries.admin.SegmentAdminService/DeleteSegment"
	SegmentAdminService_ShuffleSegmentCategories_FullMethodName = "/wildberries.admin.SegmentAdminService/ShuffleSegmentCategories"
)

// SegmentAdminServiceClient is the client API for SegmentAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentAdminServiceClient interface {
	GenerateSegments(ctx context.Context, in *GenerateSegmentsRequest, opts ...grpc.CallOption) (*GenerateSegmentsResponse, error)
	CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*CreateSegmentResponse, error)
	UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...grpc.CallOption) (*UpdateSegmentResponse, error)
	DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error)
	ShuffleSegmentCategories(ctx context.Context, in *ShuffleSegmentCategoriesRequest, opts ...grpc.CallOption) (*ShuffleSegmentCategoriesResponse, error)
}

type segmentAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentAdminServiceClient(cc grpc.ClientConnInterface) SegmentAdminServiceClient {
	return &segmentAdminServiceClient{cc}
}

func (c *segmentAdminServiceClient) GenerateSegments(ctx context.Context, in *GenerateSegmentsRequest, opts ...grpc.CallOption) (*GenerateSegmentsResponse, error) {
	out := new(GenerateSegmentsResponse)
	err := c.cc.Invoke(ctx, SegmentAdminService_GenerateSegments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentAdminServiceClient) CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*CreateSegmentResponse, error) {
	out := new(CreateSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentAdminService_CreateSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentAdminServiceClient) UpdateSegment(ctx context.Context, in *UpdateSegmentRequest, opts ...grpc.CallOption) (*UpdateSegmentResponse, error) {
	out := new(UpdateSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentAdminService_UpdateSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentAdminServiceClient) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error) {
	out := new(DeleteSegmentResponse)
	err := c.cc.Invoke(ctx, SegmentAdminService_DeleteSegment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentAdminServiceClient) ShuffleSegmentCategories(ctx context.Context, in *ShuffleSegmentCategoriesRequest, opts ...grpc.CallOption) (*ShuffleSegmentCategoriesResponse, error) {
	out := new(ShuffleSegmentCategoriesResponse)
	err := c.cc.Invoke(ctx, SegmentAdminService_ShuffleSegmentCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SegmentAdminServiceServer is the server API for SegmentAdminService service.
// All implementations must embed UnimplementedSegmentAdminServiceServer
// for forward compatibility
type SegmentAdminServiceServer interface {
	GenerateSegments(context.Context, *GenerateSegmentsRequest) (*GenerateSegmentsResponse, error)
	CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error)
	UpdateSegment(context.Context, *UpdateSegmentRequest) (*UpdateSegmentResponse, error)
	DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error)
	ShuffleSegmentCategories(context.Context, *ShuffleSegmentCategoriesRequest) (*ShuffleSegmentCategoriesResponse, error)
	mustEmbedUnimplementedSegmentAdminServiceServer()
}

// UnimplementedSegmentAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSegmentAdminServiceServer struct {
}

func (UnimplementedSegmentAdminServiceServer) GenerateSegments(context.Context, *GenerateSegmentsRequest) (*GenerateSegmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSegments not implemented")
}
func (UnimplementedSegmentAdminServiceServer) CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSegment not implemented")
}
func (UnimplementedSegmentAdminServiceServer) UpdateSegment(context.Context, *UpdateSegmentRequest) (*UpdateSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSegment not implemented")
}
func (UnimplementedSegmentAdminServiceServer) DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSegment not implemented")
}
func (UnimplementedSegmentAdminServiceServer) ShuffleSegmentCategories(context.Context, *ShuffleSegmentCategoriesRequest) (*ShuffleSegmentCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShuffleSegmentCategories not implemented")
}
func (UnimplementedSegmentAdminServiceServer) mustEmbedUnimplementedSegmentAdminServiceServer() {}

// UnsafeSegmentAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentAdminServiceServer will
// result in compilation errors.
type UnsafeSegmentAdminServiceServer interface {
	mustEmbedUnimplementedSegmentAdminServiceServer()
}

func RegisterSegmentAdminServiceServer(s grpc.ServiceRegistrar, srv SegmentAdminServiceServer) {
	s.RegisterService(&SegmentAdminService_ServiceDesc, srv)
}

func _SegmentAdminService_GenerateSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentAdminServiceServer).GenerateSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentAdminService_GenerateSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentAdminServiceServer).GenerateSegments(ctx, req.(*GenerateSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentAdminService_CreateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentAdminServiceServer).CreateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentAdminService_CreateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentAdminServiceServer).CreateSegment(ctx, req.(*CreateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentAdminService_UpdateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentAdminServiceServer).UpdateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentAdminService_UpdateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentAdminServiceServer).UpdateSegment(ctx, req.(*UpdateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentAdminService_DeleteSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentAdminServiceServer).DeleteSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentAdminService_DeleteSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentAdminServiceServer).DeleteSegment(ctx, req.(*DeleteSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentAdminService_ShuffleSegmentCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShuffleSegmentCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentAdminServiceServer).ShuffleSegmentCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SegmentAdminService_ShuffleSegmentCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentAdminServiceServer).ShuffleSegmentCategories(ctx, req.(*ShuffleSegmentCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SegmentAdminService_ServiceDesc is the grpc.ServiceDesc for SegmentAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.admin.SegmentAdminService",
	HandlerType: (*SegmentAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateSegments",
			Handler:    _SegmentAdminService_GenerateSegments_Handler,
		},
		{
			MethodName: "CreateSegment",
			Handler:    _SegmentAdminService_CreateSegment_Handler,
		},
		{
			MethodName: "UpdateSegment",
			Handler:    _SegmentAdminService_UpdateSegment_Handler,
		},
		{
			MethodName: "DeleteSegment",
			Handler:    _SegmentAdminService_DeleteSegment_Handler,
		},
		{
			MethodName: "ShuffleSegmentCategories",
			Handler:    _SegmentAdminService_ShuffleSegmentCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}

const (
	PollAdminService_GeneratePoll_FullMethodName     = "/wildberries.admin.PollAdminService/GeneratePoll"
	PollAdminService_SetPollQuestions_FullMethodName = "/wildberries.admin.PollAdminService/SetPollQuestions"
	PollAdminService_SetAnswerTree_FullMethodName    = "/wildberries.admin.PollAdminService/SetAnswerTree"
)

// PollAdminServiceClient is the client API for PollAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PollAdminServiceClient interface {
	GeneratePoll(ctx context.Context, in *GeneratePollRequest, opts ...grpc.CallOption) (*GeneratePollResponse, error)
	SetPollQuestions(ctx context.Context, in *SetPollQuestionsRequest, opts ...grpc.CallOption) (*SetPollQuestionsResponse, error)
	SetAnswerTree(ctx context.Context, in *SetAnswerTreeRequest, opts ...grpc.CallOption) (*SetAnswerTreeResponse, error)
}

type pollAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPollAdminServiceClient(cc grpc.ClientConnInterface) PollAdminServiceClient {
	return &pollAdminServiceClient{cc}
}

func (c *pollAdminServiceClient) GeneratePoll(ctx context.Context, in *GeneratePollRequest, opts ...grpc.CallOption) (*GeneratePollResponse, error) {
	out := new(GeneratePollResponse)
	err := c.cc.Invoke(ctx, PollAdminService_GeneratePoll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollAdminServiceClient) SetPollQuestions(ctx context.Context, in *SetPollQuestionsRequest, opts ...grpc.CallOption) (*SetPollQuestionsResponse, error) {
	out := new(SetPollQuestionsResponse)
	err := c.cc.Invoke(ctx, PollAdminService_SetPollQuestions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollAdminServiceClient) SetAnswerTree(ctx context.Context, in *SetAnswerTreeRequest, opts ...grpc.CallOption) (*SetAnswerTreeResponse, error) {
	out := new(SetAnswerTreeResponse)
	err := c.cc.Invoke(ctx, PollAdminService_SetAnswerTree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollAdminServiceServer is the server API for PollAdminService service.
// All implementations must embed UnimplementedPollAdminServiceServer
// for forward compatibility
type PollAdminServiceServer interface {
	GeneratePoll(context.Context, *GeneratePollRequest) (*GeneratePollResponse, error)
	SetPollQuestions(context.Context, *SetPollQuestionsRequest) (*SetPollQuestionsResponse, error)
	SetAnswerTree(context.Context, *SetAnswerTreeRequest) (*SetAnswerTreeResponse, error)
	mustEmbedUnimplementedPollAdminServiceServer()
}

// UnimplementedPollAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPollAdminServiceServer struct {
}

func (UnimplementedPollAdminServiceServer) GeneratePoll(context.Context, *GeneratePollRequest) (*GeneratePollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePoll not implemented")
}
func (UnimplementedPollAdminServiceServer) SetPollQuestions(context.Context, *SetPollQuestionsRequest) (*SetPollQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPollQuestions not implemented")
}
func (UnimplementedPollAdminServiceServer) SetAnswerTree(context.Context, *SetAnswerTreeRequest) (*SetAnswerTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAnswerTree not implemented")
}
func (UnimplementedPollAdminServiceServer) mustEmbedUnimplementedPollAdminServiceServer() {}

// UnsafePollAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollAdminServiceServer will
// result in compilation errors.
type UnsafePollAdminServiceServer interface {
	mustEmbedUnimplementedPollAdminServiceServer()
}

func RegisterPollAdminServiceServer(s grpc.ServiceRegistrar, srv PollAdminServiceServer) {
	s.RegisterService(&PollAdminService_ServiceDesc, srv)
}

func _PollAdminService_GeneratePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollAdminServiceServer).GeneratePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollAdminService_GeneratePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollAdminServiceServer).GeneratePoll(ctx, req.(*GeneratePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollAdminService_SetPollQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPollQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollAdminServiceServer).SetPollQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollAdminService_SetPollQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollAdminServiceServer).SetPollQuestions(ctx, req.(*SetPollQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollAdminService_SetAnswerTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnswerTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollAdminServiceServer).SetAnswerTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollAdminService_SetAnswerTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollAdminServiceServer).SetAnswerTree(ctx, req.(*SetAnswerTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PollAdminService_ServiceDesc is the grpc.ServiceDesc for PollAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.admin.PollAdminService",
	HandlerType: (*PollAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePoll",
			Handler:    _PollAdminService_GeneratePoll_Handler,
		},
		{
			MethodName: "SetPollQuestions",
			Handler:    _PollAdminService_SetPollQuestions_Handler,
		},
		{
			MethodName: "SetAnswerTree",
			Handler:    _PollAdminService_SetAnswerTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}

const (
	ModerationService_GetApplications_FullMethodName = "/wildberries.admin.ModerationService/GetApplications"
	ModerationService_Approve_FullMethodName         = "/wildberries.admin.ModerationService/Approve"
	ModerationService_Reject_FullMethodName          = "/wildberries.admin.ModerationService/Reject"
)

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModerationServiceClient interface {
	GetApplications(ctx context.Context, in *GetModerationApplicationsRequest, opts ...grpc.CallOption) (*GetModerationApplicationsResponse, error)
	Approve(ctx context.Context, in *ApproveModerationRequest, opts ...grpc.CallOption) (*ApproveModerationResponse, error)
	Reject(ctx context.Context, in *RejectModerationRequest, opts ...grpc.CallOption) (*RejectModerationResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) GetApplications(ctx context.Context, in *GetModerationApplicationsRequest, opts ...grpc.CallOption) (*GetModerationApplicationsResponse, error) {
	out := new(GetModerationApplicationsResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetApplications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Approve(ctx context.Context, in *ApproveModerationRequest, opts ...grpc.CallOption) (*ApproveModerationResponse, error) {
	out := new(ApproveModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_Approve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Reject(ctx context.Context, in *RejectModerationRequest, opts ...grpc.CallOption) (*RejectModerationResponse, error) {
	out := new(RejectModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_Reject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility
type ModerationServiceServer interface {
	GetApplications(context.Context, *GetModerationApplicationsRequest) (*GetModerationApplicationsResponse, error)
	Approve(context.Context, *ApproveModerationRequest) (*ApproveModerationResponse, error)
	Reject(context.Context, *RejectModerationRequest) (*RejectModerationResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedModerationServiceServer struct {
}

func (UnimplementedModerationServiceServer) GetApplications(context.Context, *GetModerationApplicationsRequest) (*GetModerationApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplications not implemented")
}
func (UnimplementedModerationServiceServer) Approve(context.Context, *ApproveModerationRequest) (*ApproveModerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedModerationServiceServer) Reject(context.Context, *RejectModerationRequest) (*RejectModerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s grpc.ServiceRegistrar, srv ModerationServiceServer) {
	s.RegisterService(&ModerationService_ServiceDesc, srv)
}

func _ModerationService_GetApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModerationApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetApplications(ctx, req.(*GetModerationApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Approve(ctx, req.(*ApproveModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Reject(ctx, req.(*RejectModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModerationService_ServiceDesc is the grpc.ServiceDesc for ModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wildberries.admin.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApplications",
			Handler:    _ModerationService_GetApplications_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _ModerationService_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _ModerationService_Reject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
